### ISSUE TITLE
Deleted Camera still shown

### ISSUE THREAD

**Issue by erdmark** [kamba4/sunders#4]
The following diskussion is about this point: https://www.openstreetmap.org/node/1955563466/history#map=19/38.08906/-0.66043&layers=D
You can see it displayed wrong at: https://kamba4.crux.uberspace.de/?lat=38.08887306&lon=-0.65981269&zoom=18 (Carrer Pleiters, on the left side)

This point is part of a building and previously existed. Then it was tagged to be a camera. Then it showed up as a camera too.
Because it´s position was wrong the camera tags have been removed, but the point still exists because it is still part of a building.
Now there is the issue that it still shows up on the map.

SuS seems to delete cameras from it´s database only if the point is deleted. It should delete cameras when only the camara-tags are removed, too.

**Comment by erdmark** [comment]
For future reference here are the screenshots:
https://trafficpixel.tk/photos/public/2018/02/github/osm.png
https://trafficpixel.tk/photos/public/2018/02/github/sus.png

**Comment by kamba4** [comment]
Thanks for your issue. I just checked the code and found out that update_camera.php only considers modifications made for the tag man_made:surveillance. Though if you transfer a surveillance node to a non-surveillance node this modification does not initiate the deletion of that camera in the SunderS database. I'm working on a fix.
