### ISSUE TITLE
Camera looks to wrong direction

### ISSUE THREAD

**Issue by AltNico** [kamba4/sunders#5]
*I hope I'm right in this issue tracker. If not, correct me, please!*

Yesterday I mapped [this camera](https://www.openstreetmap.org/node/5462645656) with the tag `camera:direction` containing `N`. After some time the camera [showed up on your wonderful map](https://kamba4.crux.uberspace.de/?lat=13.09232944&lon=-86.35641754&zoom=18) (thanks a lot for it, btw) and at first I thought I've made a mapping mistake because it look to the wrong direction. As you can see in OSM, it is indeed mapped correctly to look to the north and not to the east like shown on the map.

**Comment by kamba4** [comment]
Thanks for reporting this issue. You're right. I just checked it and also found out that all cameras with direction `N` look to direction `E`. The other 7 directions (`NE` `E` `SE` `S` `SW` `W` `NW`) seem to be ok. I'm working on a fix.
